name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore CarRentalApp.sln

      # Build project
      - name: Build
        run: dotnet build CarRentalApp.sln --no-restore --configuration Release

      # Run tests (if you have test projects)
      - name: Run tests
        run: dotnet test CarRentalApp.sln --no-build --verbosity normal
